# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tanki/Documents/src/util

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tanki/Documents/src/util

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tanki/Documents/src/util/CMakeFiles /Users/tanki/Documents/src/util/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tanki/Documents/src/util/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asset

# Build rule for target.
asset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asset
.PHONY : asset

# fast build rule for target.
asset/fast:
	$(MAKE) -f CMakeFiles/asset.dir/build.make CMakeFiles/asset.dir/build
.PHONY : asset/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named socket

# Build rule for target.
socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket
.PHONY : socket

# fast build rule for target.
socket/fast:
	$(MAKE) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/build
.PHONY : socket/fast

#=============================================================================
# Target rules for targets named dag

# Build rule for target.
dag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dag
.PHONY : dag

# fast build rule for target.
dag/fast:
	$(MAKE) -f CMakeFiles/dag.dir/build.make CMakeFiles/dag.dir/build
.PHONY : dag/fast

asset.o: asset.cpp.o

.PHONY : asset.o

# target to build an object file
asset.cpp.o:
	$(MAKE) -f CMakeFiles/asset.dir/build.make CMakeFiles/asset.dir/asset.cpp.o
.PHONY : asset.cpp.o

asset.i: asset.cpp.i

.PHONY : asset.i

# target to preprocess a source file
asset.cpp.i:
	$(MAKE) -f CMakeFiles/asset.dir/build.make CMakeFiles/asset.dir/asset.cpp.i
.PHONY : asset.cpp.i

asset.s: asset.cpp.s

.PHONY : asset.s

# target to generate assembly for a file
asset.cpp.s:
	$(MAKE) -f CMakeFiles/asset.dir/build.make CMakeFiles/asset.dir/asset.cpp.s
.PHONY : asset.cpp.s

dag.o: dag.cpp.o

.PHONY : dag.o

# target to build an object file
dag.cpp.o:
	$(MAKE) -f CMakeFiles/dag.dir/build.make CMakeFiles/dag.dir/dag.cpp.o
.PHONY : dag.cpp.o

dag.i: dag.cpp.i

.PHONY : dag.i

# target to preprocess a source file
dag.cpp.i:
	$(MAKE) -f CMakeFiles/dag.dir/build.make CMakeFiles/dag.dir/dag.cpp.i
.PHONY : dag.cpp.i

dag.s: dag.cpp.s

.PHONY : dag.s

# target to generate assembly for a file
dag.cpp.s:
	$(MAKE) -f CMakeFiles/dag.dir/build.make CMakeFiles/dag.dir/dag.cpp.s
.PHONY : dag.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/main.cpp.s
.PHONY : main.cpp.s

socket.o: socket.cpp.o

.PHONY : socket.o

# target to build an object file
socket.cpp.o:
	$(MAKE) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/socket.cpp.o
.PHONY : socket.cpp.o

socket.i: socket.cpp.i

.PHONY : socket.i

# target to preprocess a source file
socket.cpp.i:
	$(MAKE) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/socket.cpp.i
.PHONY : socket.cpp.i

socket.s: socket.cpp.s

.PHONY : socket.s

# target to generate assembly for a file
socket.cpp.s:
	$(MAKE) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/socket.cpp.s
.PHONY : socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... asset"
	@echo "... rebuild_cache"
	@echo "... util"
	@echo "... socket"
	@echo "... dag"
	@echo "... asset.o"
	@echo "... asset.i"
	@echo "... asset.s"
	@echo "... dag.o"
	@echo "... dag.i"
	@echo "... dag.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

